apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-k8s
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-1
        image: nginx:1.15
        ports:
        - containerPort: 80